"""empty message

Revision ID: 459dc1a747e4
Revises: 77219ff4194a
Create Date: 2019-11-19 20:49:19.454148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459dc1a747e4'
down_revision = '77219ff4194a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'date_created')
    op.drop_column('artists', 'date_created')
    # ### end Alembic commands ###
