"""empty message

Revision ID: 5fedecc880ff
Revises: aaccfb67a897
Create Date: 2019-11-12 21:29:01.694678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5fedecc880ff"
down_revision = "aaccfb67a897"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=120), nullable=True),
        sa.Column("genres", sa.ARRAY(sa.String(length=30)), nullable=True),
        sa.Column("image_link", sa.String(length=500), nullable=True),
        sa.Column("facebook_link", sa.String(length=120), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("seeking_venue", sa.Boolean(), nullable=True),
        sa.Column("seeking_description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("address", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=120), nullable=True),
        sa.Column("image_link", sa.String(length=500), nullable=True),
        sa.Column("facebook_link", sa.String(length=120), nullable=True),
        sa.Column("genres", sa.ARRAY(sa.String(length=30)), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("seeking_talent", sa.Boolean(), nullable=True),
        sa.Column("seeking_description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"],),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("Venue")
    op.drop_table("Artist")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Artist",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Artist_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "city", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column(
            "state", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column(
            "genres",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "image_link",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "facebook_link",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="Artist_pkey"),
    )
    op.create_table(
        "Venue",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Venue_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "city", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column(
            "state", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column(
            "address",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "phone", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column(
            "image_link",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "facebook_link",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="Venue_pkey"),
    )
    op.drop_table("shows")
    op.drop_table("venues")
    op.drop_table("artists")
    # ### end Alembic commands ###
