"""empty message

Revision ID: 77219ff4194a
Revises: d0605c00c98e
Create Date: 2019-11-18 18:22:03.915031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77219ff4194a"
down_revision = "d0605c00c98e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artists", "city", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "artists",
        "genres",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
        nullable=False,
    )
    op.alter_column(
        "artists", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "artists",
        "state",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "venues",
        "genres",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "venues",
        "genres",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
        nullable=True,
    )
    op.alter_column(
        "artists", "state", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "artists", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "artists",
        "genres",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=30)),
        nullable=True,
    )
    op.alter_column(
        "artists", "city", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    # ### end Alembic commands ###
